from __future__ import annotations

import subprocess
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from bureau import events
from bureau.memory import Memory
from bureau.models import ReviewerFinding, RunSummary
from bureau.run_manager import get_run, write_run_summary
from bureau.state import Escalation, EscalationReason, Phase


def pr_create_node(state: dict[str, Any]) -> dict[str, Any]:
    with events.phase(Phase.PR_CREATE):
        run_id = state["run_id"]
        repo_path = state["repo_path"]
        spec_path = state["spec_path"]
        spec = state.get("spec")

        spec_name = spec.name if spec else Path(spec_path).stem
        branch = state.get("branch_name") or (spec.branch if spec else f"feat/unknown-{run_id[:8]}")

        ralph_rounds_dicts = state.get("ralph_rounds", [])
        reviewer_findings_dicts = state.get("reviewer_findings", [])
        reviewer_findings = [ReviewerFinding.model_validate(f) for f in reviewer_findings_dicts]

        frs_addressed = sorted(
            {f.ref_id for f in reviewer_findings if f.type == "requirement" and f.verdict == "met"}
        )

        reviewer_verdict = (
            ralph_rounds_dicts[-1].get("reviewer_verdict", "pass") if ralph_rounds_dicts else "pass"
        )

        duration = _calc_duration(run_id)
        completed_at = datetime.now(timezone.utc).isoformat()

        run_summary = RunSummary(
            run_id=run_id,
            spec_name=spec_name,
            spec_path=spec_path,
            branch=branch,
            ralph_rounds=len(ralph_rounds_dicts),
            frs_addressed=frs_addressed,
            reviewer_verdict=reviewer_verdict,
            reviewer_findings=reviewer_findings,
            pr_url="",
            duration_seconds=duration,
            completed_at=completed_at,
        )

        pr_title = spec_name
        pr_body = _render_pr_body(run_summary)

        try:
            result = subprocess.run(
                ["gh", "pr", "create", "--title", pr_title, "--body", pr_body],
                cwd=repo_path,
                capture_output=True,
                text=True,
                timeout=60,
            )
        except Exception as exc:
            return _escalate(state, f"PR creation failed: {exc}", EscalationReason.PR_FAILED)

        if result.returncode != 0:
            return _escalate(
                state,
                f"PR creation failed: {(result.stderr or result.stdout).strip()}",
                EscalationReason.PR_FAILED,
            )

        pr_url = result.stdout.strip()
        run_summary = RunSummary(**{**run_summary.model_dump(), "pr_url": pr_url})

        mem = Memory(run_id)
        mem.write("run_summary", run_summary.model_dump())

        write_run_summary(state, "pass")

    events.emit(events.PR_CREATED, id=run_id, pr=pr_url, duration=f"{duration:.1f}s")

    return {
        **state,
        "run_summary": run_summary.model_dump(),
        "phase": Phase.COMPLETE,
    }


def _calc_duration(run_id: str) -> float:
    try:
        record = get_run(run_id)
        started = datetime.fromisoformat(record.started_at)
        return (datetime.now(timezone.utc) - started).total_seconds()
    except Exception:
        return 0.0


def _render_pr_body(summary: RunSummary) -> str:
    lines = [
        "## Bureau Run Summary",
        "",
        "| Field | Value |",
        "|-------|-------|",
        f"| Run ID | `{summary.run_id}` |",
        f"| Feature | {summary.spec_name} |",
        f"| Spec | `{summary.spec_path}` |",
        f"| Branch | `{summary.branch}` |",
        f"| Reviewer Verdict | `{summary.reviewer_verdict}` |",
        f"| Ralph Loop Rounds | {summary.ralph_rounds} |",
        f"| Duration | {summary.duration_seconds:.1f}s |",
        f"| Completed | {summary.completed_at} |",
        "",
        "## Functional Requirements Addressed",
        "",
    ]

    if summary.frs_addressed:
        lines.extend(f"- {fr}" for fr in summary.frs_addressed)
    else:
        lines.append("_(none recorded)_")

    lines += ["", "## Reviewer Findings", ""]

    if summary.reviewer_findings:
        for f in summary.reviewer_findings:
            icon = "✅" if f.verdict == "met" else ("🚨" if f.verdict == "violation" else "⚠️")
            lines.append(f"- {icon} **{f.ref_id}** ({f.type}): {f.detail}")
    else:
        lines.append("_(no findings recorded)_")

    lines += [
        "",
        "---",
        "_Generated by [bureau](https://github.com/fancy-bread/bureau) — Spec file in. PR out._",
    ]

    return "\n".join(lines)


def _escalate(state: dict[str, Any], reason: str, escalation_reason: EscalationReason) -> dict[str, Any]:
    escalation = Escalation(
        run_id=state["run_id"],
        phase=Phase.PR_CREATE,
        reason=escalation_reason,
        what_happened=reason,
        what_is_needed="Ensure `gh` CLI is installed, authenticated, and the repo has a GitHub remote.",
        options=[
            "Run `gh auth status` to verify authentication",
            "Run `git remote -v` to verify remote configuration",
            "Abort this run with `bureau abort <run-id>`",
        ],
        timestamp=datetime.now(timezone.utc).isoformat(),
    )
    return {
        **state,
        "escalations": state.get("escalations", []) + [escalation],
        "phase": Phase.ESCALATE,
        "_route": "escalate",
    }
